# This Yaml file contains the parameters of the different tasks

qrc_params:
  L: 2
  Js : 1
  fixed_h: 3
  fixed_W: 0.01
  dt: 0.5
  N_rep: 1
  Vmp: 1
  Dmp: 1
  back_action: True
  monitor_axis: 'x'
  meas_strength: 0.2

flags:
  obs: False
  rewrite: False
  performance: True
  load_obs: True

esn_params:
  N_esn: 45
  g: 0.25
  l: 0.001
  N_esn_solely: 180

common_params:
  task_name: "Qinp"
  qtasks: ['Tracerho2']
  N_iter: 1
  seed: 48
  store: True
  inp_type: 'qubit'

perf_params:
  pm: "Fidelity"
  n_min_delay: 0
  n_max_delay: 15
  ratio_delay_qrc: 0.5
  axis: ['y']
  caxis: ['y']
  ccaxis: []
  onlyesn: False
  qrc_prep_perf: False

# Particular tasks

sweeps:
  sweep1:
    ratio_delay_qrc: [0.0, 0.5, 1.0]
  
  sweep2:
    axis: [['z'],['x'],['y'],['x','y'], ['z','x','y']]
    caxis: [['z'],['x'],['y'],['x','y'], ['z','x','y']]
    N_esn_solely: [90, 90, 90, 135, 180]

  sweep3:
    L: [5,6,7,8,9,10]
    N_esn: [15,21,28,36,45,55]

sweepslurm:
  z:
    axis: ['z']
    N_esn_solely: 45
  x:
    axis: ['x']
    N_esn_solely: 45
  y:
    axis: ['y']
    N_esn_solely: 45
  xy:
    axis: ['x','y']
    N_esn_solely: 45
  zxy:
    axis: ['z','x','y']
    N_esn_solely: 45

# Optimized quantum task parameters

all_qtasks:
  Tracerho2:
    qtasks: ['Tracerho2']
    pm: "NMSE"
    g: 0.25
    l: 0.001
    ratio_delay_qrc: 1.0

  Entropy:
    qtasks: ['Entropy']
    pm: "NMSE"
    g: 0.25
    l: 0.001
    ratio_delay_qrc: 0.5

  Sigman:
    qtasks: ['Sigman']
    pm: "NMSE"
    g: 4
    l: 0.00001
    ratio_delay_qrc: 0.0

  Entanglement:
    qtasks: ['Entanglement']
    pm: "NMSE"
    g: 0.25
    l: 0.001
    ratio_delay_qrc: 1.0

  Fidelity:
    qtasks: ['Fidelity']
    pm: "Fidelity"
    g: 4
    l: 0.00001
    ratio_delay_qrc: 0.0
  
  FidelityPurity:
    qtasks: ['Fidelity']
    pm: "FidelityPurity"
    g: 4
    l: 0.00001
    ratio_delay_qrc: 0.0
